/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HelpEditChartsPanel.java
 *
 * Created on Nov 5, 2010, 1:06:41 PM
 */

/**
 *
 * @author gary
 */
import java.awt.*;

public class HelpEditChartsPanel extends javax.swing.JPanel {

    /** Creates new form HelpEditChartsPanel */
    public HelpEditChartsPanel() {
        initComponents();
        jTextArea1.setSelectionStart(0);
        jTextArea1.setSelectionEnd(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18));
        jLabel1.setText("How To Edit Charts in SILKin");

        jScrollPane1.setViewportView(jTextArea1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("*** Moving People and Unions\nClick on and drag a person or union symbol to move it. The links will automatically be redrawn. \nIf you hold down the SHIFT key and move a union, you will also move the immediate nuclear \nfamily associated with that union. If you hold down the ALT (Mac COMMAND) key while moving a \nunion you will move the entire lineage descended from that union.\n\n*** Deleting relationships\nDrag  a person to either the top (if they are a parent/spouse) or bottom (if they are a child/sibling)\nof a union. If there was a relationship, it will be deleted.\n\n*** Deleting People or Unions\nHold down the CONTROL (CTRL) key and click on a symbol. This will be deleted along with its \nrelationships. BE CAREFUL. Do not delete the person if you only need to delete a relationship \n(see above).\n\nThe 'Clear All' entry under the File menu deletes all people, unions and relationships.\nNOTE: This is not yet implemented.\n\n*** Entering Data about People and Unions\nClick on a person or union. The symbol should turn blue. You can then fill in the information\nat the top of the window. Information is not recorded unless you change to a different symbol. \nNormally this suggests that the last entry should be followed by clicking on some other person \nor union. \n\nNOTE that the month and day portion of all dates (birth, death, marriage and divorce) are \nconverted by SILKin into a standard \"medium-length\" format (e.g. Feb 29) but you may enter \nthem in either that format or as numbers (e.g. 2/29).");
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(294, 294, 294)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(106, 106, 106)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 640, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 292, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
