/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ActionBoxInstructions.java
 *
 * Created on Feb 24, 2011, 1:49:21 PM
 */

/**
 *
 * @author gary
 */
public class ActionBoxInstructions extends javax.swing.JPanel {

    /** Creates new form ActionBoxInstructions */
    public ActionBoxInstructions() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Action Box: Instructions"));
        setPreferredSize(new java.awt.Dimension(425, 300));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Select a Suggestion from the drop-down menu above. \nThis Action Box will be replaced by an Action Box \ntailored to the type of suggestion you selected. \n\nIn all Action Boxes, there will be one or more decisions \nor entries to make. You may change your mind or edit \nyour entries as many times as you wish. \nNo action will be taken on your decisions until \nyou click the \"Done\" button in the lower right corner \nof the Action Box. \n\nEven if you change your mind later, you can re-visit a \nSuggestion and \"Un-Do.\"\n\nIf you type into a text box like this one, do not hit \n\"Enter\" or \"Return\". Your lines of text will wrap \naround automatically. There is no limit on the length \nof text box entries.");
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
