
import java.util.*;
import javax.swing.*;

/** This class creates the Action Box for an Anomaly in the
 * {@link DecisionFrame} whenever the suggestion chosen by User is an
 * Anomaly.
 *
 * @author  Gary Morris, University of Pennsylvania		garymorris2245@verizon.net
 *
 * Created on June 24, 2011, 3:21:57 PM
 */
public class ActionAnomaly extends javax.swing.JPanel {

    DecisionFrame papa;
    Anomaly anna;
    int suggNmbr;
    ArrayList<Object> oddballs;

    /** Creates new form ActionAnomaly */
    public ActionAnomaly() {
        initComponents();
    }

    public ActionAnomaly(DecisionFrame frame) {
        initComponents();
        papa = frame;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        oddballLabel = new javax.swing.JLabel();
        oddballDyadsCombo = new javax.swing.JComboBox();
        egoLabel = new javax.swing.JLabel();
        egoNames = new javax.swing.JLabel();
        alterLabel = new javax.swing.JLabel();
        alterNames = new javax.swing.JLabel();
        noActionBtn = new javax.swing.JRadioButton();
        dyadCorrectBtn = new javax.swing.JRadioButton();
        dyadWrongBtn = new javax.swing.JRadioButton();
        correctionByn = new javax.swing.JRadioButton();
        correctedKinTerm = new javax.swing.JTextField();
        recordBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Action Box: Anomaly"));

        oddballLabel.setText("Questionable Dyads");

        oddballDyadsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ego:  12  Alter:   6   Kin Term:  grandpaw", "Ego:    5  Alter:  14  Kin Term:  grampa" }));

        egoLabel.setText("Ego: ");

        egoNames.setText("______");

        alterLabel.setText("Alter: ");

        alterNames.setText("______");

        buttonGroup1.add(noActionBtn);
        noActionBtn.setSelected(true);
        noActionBtn.setText("No Action");

        buttonGroup1.add(dyadCorrectBtn);
        dyadCorrectBtn.setText("This dyad is correct.");

        buttonGroup1.add(dyadWrongBtn);
        dyadWrongBtn.setText("This dyad is wrong.  Delete it.");

        buttonGroup1.add(correctionByn);
        correctionByn.setText("Correct the kin term to ");
        correctionByn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctionBynActionPerformed(evt);
            }
        });

        recordBtn.setText("Record Decision on This Dyad");
        recordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(dyadCorrectBtn)
                            .addContainerGap())
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                            .add(oddballLabel)
                            .add(144, 144, 144))
                        .add(layout.createSequentialGroup()
                            .add(oddballDyadsCombo, 0, 384, Short.MAX_VALUE)
                            .addContainerGap())
                        .add(layout.createSequentialGroup()
                            .add(egoLabel)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(egoNames)
                            .addContainerGap(314, Short.MAX_VALUE))
                        .add(layout.createSequentialGroup()
                            .add(alterLabel)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(alterNames)
                            .addContainerGap(313, Short.MAX_VALUE))
                        .add(layout.createSequentialGroup()
                            .add(noActionBtn)
                            .addContainerGap(306, Short.MAX_VALUE))
                        .add(layout.createSequentialGroup()
                            .add(correctionByn)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(correctedKinTerm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .add(dyadWrongBtn))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(recordBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(oddballLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(oddballDyadsCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(egoLabel)
                    .add(egoNames))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(alterLabel)
                    .add(alterNames))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(noActionBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dyadCorrectBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dyadWrongBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(correctionByn)
                    .add(correctedKinTerm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 41, Short.MAX_VALUE)
                .add(recordBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void load(Anomaly a, int nmbr) {
        anna = a;
        suggNmbr = nmbr;
        loadOddballs();
        oddballDyadsCombo.setSelectedIndex(0);
        loadNames(0);
    }

    void loadOddballs() {
        oddballs = anna.findOddballs();
        String[] dyStrings = new String[oddballs.size()];
        String pad1, pad2;
        for (int i = 0; i < oddballs.size(); i++) {
            Dyad d = (Dyad) oddballs.get(i);
            pad1 = makePad(d.ego.serialNmbr);
            pad2 = makePad(d.alter.serialNmbr);
            String s = "Ego: " + pad1 + d.ego.serialNmbr;
            s += "  Alter: " + pad2 + d.alter.serialNmbr;
            s += "  Kin Term: " + d.kinTerm;
            dyStrings[i] = s;
        }
        oddballDyadsCombo.setModel(new DefaultComboBoxModel(dyStrings));
    }

    String makePad(int num) {
        if (num < 10) {
            return "  ";
        } else if (num < 100) {
            return " ";
        } else {
            return "";
        }
    }

    void loadNames(int num) {
        Dyad d = (Dyad) oddballs.get(num);
        egoNames.setText(d.ego.firstNames + " " + d.ego.surname);
        alterNames.setText(d.alter.firstNames + " " + d.alter.surname);
        correctedKinTerm.setText("");
        correctedKinTerm.setEditable(false);
        noActionBtn.setSelected(true);
    }

    private void recordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recordBtnActionPerformed

    private void correctionBynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctionBynActionPerformed
        correctedKinTerm.setEditable(true);
    }//GEN-LAST:event_correctionBynActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alterLabel;
    private javax.swing.JLabel alterNames;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField correctedKinTerm;
    private javax.swing.JRadioButton correctionByn;
    private javax.swing.JRadioButton dyadCorrectBtn;
    private javax.swing.JRadioButton dyadWrongBtn;
    private javax.swing.JLabel egoLabel;
    private javax.swing.JLabel egoNames;
    private javax.swing.JRadioButton noActionBtn;
    private javax.swing.JComboBox oddballDyadsCombo;
    private javax.swing.JLabel oddballLabel;
    private javax.swing.JButton recordBtn;
    // End of variables declaration//GEN-END:variables
}
