import java.util.*;
import javax.swing.*;

/** This class creates the Action Box for an OverlapCandidate in the
 * {@link DecisionFrame} whenever the suggestion chosen by User is an
 * OverlapCandidate.
 *
 * @author  Gary Morris, University of Pennsylvania		garymorris2245@verizon.net
 *
 * Created on June 24, 2011, 3:21:57 PM
 */

public class ActionOverlap extends javax.swing.JPanel {

    DecisionFrame papa;
    OverlapCandidate oc;
    int suggNmbr;
    String[] emptyModel = { "Overlapping Dyads for Review" };
    ArrayList<Dyad> olapDyads;

    /** Creates new form ActionOverlap */
    public ActionOverlap() {
        initComponents();
    }

    public ActionOverlap(DecisionFrame frame) {
        initComponents();
        papa = frame;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        olapNoActionBtn = new javax.swing.JRadioButton();
        overlapOKBtn = new javax.swing.JRadioButton();
        olapNotOKBtn = new javax.swing.JRadioButton();
        notesScrollPane = new javax.swing.JScrollPane();
        notesText = new javax.swing.JTextArea();
        doneBtn = new javax.swing.JButton();
        term1Label = new javax.swing.JLabel();
        term1Text = new javax.swing.JLabel();
        term2Label = new javax.swing.JLabel();
        term2Text = new javax.swing.JLabel();
        overlappingDyadComboBox = new javax.swing.JComboBox();
        dyadOKBtn = new javax.swing.JRadioButton();
        dyadDeleteBtn = new javax.swing.JRadioButton();
        dyadEditBtn = new javax.swing.JRadioButton();
        correctKinTermText = new javax.swing.JTextField();
        recordDyadEditBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Action Box: Overlapping Terms"));

        buttonGroup1.add(olapNoActionBtn);
        olapNoActionBtn.setSelected(true);
        olapNoActionBtn.setText("No Action");

        buttonGroup1.add(overlapOKBtn);
        overlapOKBtn.setText("This overlap is OK.");

        buttonGroup1.add(olapNotOKBtn);
        olapNotOKBtn.setText("This overlap is NOT correct. I will edit the dyads below.");
        olapNotOKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olapNotOKBtnActionPerformed(evt);
            }
        });

        notesScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Notes on this Overlap\n"));

        notesText.setColumns(20);
        notesText.setRows(5);
        notesScrollPane.setViewportView(notesText);

        doneBtn.setText("Done");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        term1Label.setText("Term1: ");

        term1Text.setText("_____");

        term2Label.setText("Term2: ");

        term2Text.setText("_____");

        overlappingDyadComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Overlapping Dyads for Review" }));

        buttonGroup2.add(dyadOKBtn);
        dyadOKBtn.setText("Confirm this dyad.");
        dyadOKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dyadOKBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(dyadDeleteBtn);
        dyadDeleteBtn.setText("Delete this dyad.");
        dyadDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dyadDeleteBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(dyadEditBtn);
        dyadEditBtn.setText("Correct the kin term to ");
        dyadEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dyadEditBtnActionPerformed(evt);
            }
        });

        correctKinTermText.setEditable(false);

        recordDyadEditBtn.setText("Record decision on this dyad.");
        recordDyadEditBtn.setEnabled(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(term1Label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(term1Text)
                        .add(95, 95, 95)
                        .add(term2Label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(term2Text)
                        .add(136, 136, 136))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(recordDyadEditBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 95, Short.MAX_VALUE)
                        .add(doneBtn)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(notesScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(overlapOKBtn)
                                        .add(olapNoActionBtn))
                                    .add(109, 109, 109))
                                .add(olapNotOKBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(layout.createSequentialGroup()
                                        .add(dyadOKBtn)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(dyadDeleteBtn))
                                    .add(overlappingDyadComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 366, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(layout.createSequentialGroup()
                                        .add(dyadEditBtn)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(correctKinTermText)))
                                .add(15, 15, 15)))
                        .add(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(term1Label)
                    .add(term1Text)
                    .add(term2Label)
                    .add(term2Text))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(olapNoActionBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(overlapOKBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(olapNotOKBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(overlappingDyadComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dyadOKBtn)
                    .add(dyadDeleteBtn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dyadEditBtn)
                    .add(correctKinTermText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 11, Short.MAX_VALUE)
                .add(notesScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(doneBtn)
                    .add(recordDyadEditBtn)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void load(OverlapCandidate olap, int nmbr) {
        oc = olap;
        suggNmbr = nmbr;
        term1Text.setText(oc.kinTerm);
        term2Text.setText(oc.otherTerm);
        olapNoActionBtn.setSelected(true);
        correctKinTermText.setText("");
        overlappingDyadComboBox.setModel(new DefaultComboBoxModel(emptyModel));
        dyadDeleteBtn.setSelected(false);
        dyadOKBtn.setSelected(false);
        dyadEditBtn.setSelected(false);
        correctKinTermText.setEditable(false);
        recordDyadEditBtn.setEnabled(false);
        olapDyads = makeOlapDyadList();
    }


    ArrayList<Dyad> makeOlapDyadList() {
        ArrayList<Dyad> dys = new ArrayList<Dyad>();
        for (Object o : oc.ktermDyads) {
            Dyad kd = (Dyad)o;
            if (oc.intersection.contains(kd.pcString)) {
                dys.add(kd);
            }
        }
        for (Object o : oc.otherTermDyads) {
            Dyad kd = (Dyad)o;
            if (oc.intersection.contains(kd.pcString)) {
                dys.add(kd);
            }
        }
        return dys;
    }

    void resetDyadComboBox() {
        // Must think thru how to know when all dyads have been dealt with,
        // whether to let User re-edit a dyad, or ignore some dyads.
        // MAYBE a separate list of processedDyads (don't remove from olapDyads,
        // just mark them "DONE" in combo box.
        String[] model = new String[olapDyads.size()];
        String line;
        int cntr = 0;
        for (Dyad d : olapDyads) {
            line = "Ego: #" + d.ego.serialNmbr;
            line += "   Alter: #" + d.alter.serialNmbr;
            line += "   kin term: " + d.kinTerm;
            line += "   kin type: " + d.pcString;
            model[cntr++] = line;
        }
        overlappingDyadComboBox.setModel(new DefaultComboBoxModel(model));
        correctKinTermText.setEditable(true);
    }


    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        if (overlapOKBtn.isSelected() || olapNotOKBtn.isSelected()) {
            papa.markProcessed(suggNmbr);
        }
    }//GEN-LAST:event_doneBtnActionPerformed

    private void olapNotOKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olapNotOKBtnActionPerformed
        // activate the dyad radio btns, RecordDyadEditBtn and load combo box.
        dyadOKBtn.setSelected(true);
        recordDyadEditBtn.setEnabled(true);
        resetDyadComboBox();
    }//GEN-LAST:event_olapNotOKBtnActionPerformed

    private void dyadOKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dyadOKBtnActionPerformed
        // TODO annotate the dyad (and remove from combo???)
    }//GEN-LAST:event_dyadOKBtnActionPerformed

    private void dyadDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dyadDeleteBtnActionPerformed
        // TODO confirmation pop-up, then delete.
    }//GEN-LAST:event_dyadDeleteBtnActionPerformed

    private void dyadEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dyadEditBtnActionPerformed
        // TODO amend dyad in all locations
    }//GEN-LAST:event_dyadEditBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField correctKinTermText;
    private javax.swing.JButton doneBtn;
    private javax.swing.JRadioButton dyadDeleteBtn;
    private javax.swing.JRadioButton dyadEditBtn;
    private javax.swing.JRadioButton dyadOKBtn;
    private javax.swing.JScrollPane notesScrollPane;
    private javax.swing.JTextArea notesText;
    private javax.swing.JRadioButton olapNoActionBtn;
    private javax.swing.JRadioButton olapNotOKBtn;
    private javax.swing.JRadioButton overlapOKBtn;
    private javax.swing.JComboBox overlappingDyadComboBox;
    private javax.swing.JButton recordDyadEditBtn;
    private javax.swing.JLabel term1Label;
    private javax.swing.JLabel term1Text;
    private javax.swing.JLabel term2Label;
    private javax.swing.JLabel term2Text;
    // End of variables declaration//GEN-END:variables

}
