
import javax.swing.*;

/** The EditPrefsWindow is where Learning Parameters are set.
 *  It simply displays the values and allows editing of them.
 *  
 * These values are saved to and reloaded from the SILK file.
 *
 * Created on Sep 14, 2011, 5:55:11 PM
 * @author gary
 */
public class EditPrefsWindow extends JFrame {

    private static final int ignorMaxVal = 10;
    private static final int ignorMinVal = 0;
    private static final int maxMaxVal = 40;
    private static final int maxMinVal = 0;
    boolean loading = true;

    /** Creates new form EditPrefsWindow */
    public EditPrefsWindow() {
        initComponents();
        loadValues();
    }

    void loadValues() {
        int igVal = Context.current.ignorableP,
            mxVal = Context.current.maxNoiseP;
        ignorableSlider.setMinimum(ignorMinVal);
        // Oddly, setMaximum also sets the slider val = max
        ignorableSlider.setMaximum(ignorMaxVal);
        ignorableSlider.setMajorTickSpacing(5);
        ignorableSlider.setMinorTickSpacing(1);
        ignorableSlider.setPaintTicks(true);
        ignorableSlider.setValue(igVal);
        ignorableField.setText(igVal + "%");
        ignorableField.setEditable(false);
        maxSlider.setMinimum(maxMinVal);
        maxSlider.setMaximum(maxMaxVal);
        maxSlider.setMajorTickSpacing(10);
        maxSlider.setMinorTickSpacing(5);
        maxSlider.setPaintTicks(true);
        maxSlider.setValue(mxVal);
        maxField.setText(mxVal + "%");
        maxField.setEditable(false);
        polygamyCkBox.setSelected(Context.current.polygamyPermit);
        inductionCkBox.setSelected(Context.current.doInduction);
        subpatternCkBox.setSelected(Context.current.doBaseCBs);
        surnameCheckBox.setSelected(SIL_Edit.editWindow.getPPanel().surnameNormallyCaptured);
        birthdateCheckBox.setSelected(SIL_Edit.editWindow.getPPanel().birthDateNormallyCaptured);
        String fileName = SIL_Edit.editWindow.chart.saveFile.getName();
        setTitle("Edit Preferences for " + fileName);
        loading = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        polygamyHelp = new javax.swing.JButton();
        inductionHelp = new javax.swing.JButton();
        polygamyCkBox = new javax.swing.JCheckBox();
        subpatternHelp = new javax.swing.JButton();
        inductionCkBox = new javax.swing.JCheckBox();
        ignorableSlider = new javax.swing.JSlider();
        ignorableLabel = new javax.swing.JLabel();
        subpatternCkBox = new javax.swing.JCheckBox();
        maxField = new javax.swing.JTextField();
        maxLabel = new javax.swing.JLabel();
        ignoreHelp = new javax.swing.JButton();
        ignorableField = new javax.swing.JTextField();
        maxHelp = new javax.swing.JButton();
        maxSlider = new javax.swing.JSlider();
        doneBtn = new javax.swing.JButton();
        surnameCheckBox = new javax.swing.JCheckBox();
        birthdateCheckBox = new javax.swing.JCheckBox();
        normalCaptureHelpBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        polygamyHelp.setForeground(new java.awt.Color(255, 0, 0));
        polygamyHelp.setText("?");
        polygamyHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polygamyHelpActionPerformed(evt);
            }
        });

        inductionHelp.setForeground(new java.awt.Color(255, 0, 0));
        inductionHelp.setText("?");
        inductionHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inductionHelpActionPerformed(evt);
            }
        });

        polygamyCkBox.setText("Polygamy Permitted?");
        polygamyCkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polygamyCkBoxActionPerformed(evt);
            }
        });

        subpatternHelp.setForeground(new java.awt.Color(255, 0, 0));
        subpatternHelp.setText("?");
        subpatternHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subpatternHelpActionPerformed(evt);
            }
        });

        inductionCkBox.setText("Do Pure Induction");
        inductionCkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inductionCkBoxActionPerformed(evt);
            }
        });

        ignorableSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ignorableSliderStateChanged(evt);
            }
        });

        ignorableLabel.setText("Ignorable %");

        subpatternCkBox.setText("Do Sub-Pattern Matches");
        subpatternCkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subpatternCkBoxActionPerformed(evt);
            }
        });

        maxField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        maxField.setText("25");

        maxLabel.setText("Max %");

        ignoreHelp.setForeground(new java.awt.Color(255, 0, 0));
        ignoreHelp.setText("?");
        ignoreHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignoreHelpActionPerformed(evt);
            }
        });

        ignorableField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ignorableField.setText("5");
        ignorableField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignorableFieldActionPerformed(evt);
            }
        });

        maxHelp.setForeground(new java.awt.Color(255, 0, 0));
        maxHelp.setText("?");
        maxHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxHelpActionPerformed(evt);
            }
        });

        maxSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maxSliderStateChanged(evt);
            }
        });

        doneBtn.setText("Done");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        surnameCheckBox.setText("Surname Normally Captured?");
        surnameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameCheckBoxActionPerformed(evt);
            }
        });

        birthdateCheckBox.setText("Birth Date Normally Captured?");
        birthdateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateCheckBoxActionPerformed(evt);
            }
        });

        normalCaptureHelpBtn.setForeground(new java.awt.Color(255, 0, 0));
        normalCaptureHelpBtn.setText("?");
        normalCaptureHelpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalCaptureHelpBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(maxLabel)
                            .add(ignorableLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(ignorableField)
                            .add(maxField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(subpatternCkBox)
                            .add(polygamyCkBox)
                            .add(inductionCkBox)
                            .add(surnameCheckBox)
                            .add(birthdateCheckBox))
                        .add(7, 7, 7)))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(layout.createSequentialGroup()
                            .add(ignorableSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(ignoreHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(maxSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(maxHelp, 0, 0, Short.MAX_VALUE)))
                    .add(subpatternHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(inductionHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, normalCaptureHelpBtn, 0, 0, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, polygamyHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(391, Short.MAX_VALUE)
                .add(doneBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(ignorableSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(ignorableLabel)
                        .add(ignorableField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(ignoreHelp))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(maxLabel)
                        .add(maxField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(maxSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(maxHelp))
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(subpatternCkBox)
                    .add(subpatternHelp))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(inductionHelp)
                    .add(inductionCkBox))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(polygamyHelp)
                    .add(polygamyCkBox))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(surnameCheckBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(birthdateCheckBox)
                        .add(28, 28, 28)
                        .add(doneBtn))
                    .add(layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(normalCaptureHelpBtn)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void polygamyCkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polygamyCkBoxActionPerformed
        // TODO add your handling code here:}//GEN-LAST:event_polygamyCkBoxActionPerformed
        if (loading) {
            return;
        }
        Context.current.polygamyPermit = polygamyCkBox.isSelected();
        SIL_Edit.editWindow.chart.dirty = true;
    }
        private void ignorableFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignorableFieldActionPerformed
        // TODO add your handling code here:}//GEN-LAST:event_ignorableFieldActionPerformed
    }
        private void ignorableSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ignorableSliderStateChanged
            if (loading) {
                return;
            }
            JSlider iggy = (JSlider) evt.getSource();
            if (!iggy.getValueIsAdjusting()) {
                int val = (int) iggy.getValue();
                ignorableField.setText(val + "%");
                SIL_Edit.editWindow.chart.dirty = true;
                Context.current.ignorableP = val;
            }
    }//GEN-LAST:event_ignorableSliderStateChanged

    private void maxSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxSliderStateChanged
        if (loading) {
            return;
        }
        JSlider maxy = (JSlider) evt.getSource();
        if (!maxy.getValueIsAdjusting()) {
            int val = (int) maxy.getValue();
            maxField.setText(val + "%");
            Context.current.maxNoiseP = val;
            SIL_Edit.editWindow.chart.dirty = true;
        }
    }//GEN-LAST:event_maxSliderStateChanged

    private void subpatternCkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subpatternCkBoxActionPerformed
        if (loading) {
            return;
        }
        Context.current.doBaseCBs = subpatternCkBox.isSelected();
        SIL_Edit.editWindow.chart.dirty = true;
    }//GEN-LAST:event_subpatternCkBoxActionPerformed

    private void inductionCkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inductionCkBoxActionPerformed
        if (loading) {
            return;
        }
        Context.current.doInduction = inductionCkBox.isSelected();
        SIL_Edit.editWindow.chart.dirty = true;
    }//GEN-LAST:event_inductionCkBoxActionPerformed

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        dispose();
    }//GEN-LAST:event_doneBtnActionPerformed

    private void ignoreHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignoreHelpActionPerformed
        HelpFrame.help.displayPage(HelpFrame.PREFS, "ignore");
    }//GEN-LAST:event_ignoreHelpActionPerformed

    private void maxHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxHelpActionPerformed
        HelpFrame.help.displayPage(HelpFrame.PREFS, "max");
    }//GEN-LAST:event_maxHelpActionPerformed

    private void subpatternHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subpatternHelpActionPerformed
        HelpFrame.help.displayPage(HelpFrame.PREFS, "sub");
    }//GEN-LAST:event_subpatternHelpActionPerformed

    private void inductionHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inductionHelpActionPerformed
        HelpFrame.help.displayPage(HelpFrame.PREFS, "induce");
    }//GEN-LAST:event_inductionHelpActionPerformed

    private void polygamyHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polygamyHelpActionPerformed
        HelpFrame.help.displayPage(HelpFrame.PREFS, "poly");
    }//GEN-LAST:event_polygamyHelpActionPerformed

    private void normalCaptureHelpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalCaptureHelpBtnActionPerformed
        HelpFrame.help.displayPage(HelpFrame.PREFS, "capture");
    }//GEN-LAST:event_normalCaptureHelpBtnActionPerformed

    private void surnameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameCheckBoxActionPerformed
         if (loading) {
            return;
        }
        SIL_Edit.editWindow.getPPanel().surnameNormallyCaptured = surnameCheckBox.isSelected();
        SIL_Edit.editWindow.getPPanel().buildFocusFields();
        SIL_Edit.editWindow.chart.dirty = true;
    }//GEN-LAST:event_surnameCheckBoxActionPerformed

    private void birthdateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdateCheckBoxActionPerformed
        if (loading) {
            return;
        }
        SIL_Edit.editWindow.getPPanel().birthDateNormallyCaptured = birthdateCheckBox.isSelected();
        SIL_Edit.editWindow.getPPanel().buildFocusFields();
        SIL_Edit.editWindow.chart.dirty = true;
    }//GEN-LAST:event_birthdateCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPrefsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPrefsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPrefsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPrefsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EditPrefsWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox birthdateCheckBox;
    private javax.swing.JButton doneBtn;
    private javax.swing.JTextField ignorableField;
    private javax.swing.JLabel ignorableLabel;
    private javax.swing.JSlider ignorableSlider;
    private javax.swing.JButton ignoreHelp;
    private javax.swing.JCheckBox inductionCkBox;
    private javax.swing.JButton inductionHelp;
    private javax.swing.JTextField maxField;
    private javax.swing.JButton maxHelp;
    private javax.swing.JLabel maxLabel;
    private javax.swing.JSlider maxSlider;
    private javax.swing.JButton normalCaptureHelpBtn;
    private javax.swing.JCheckBox polygamyCkBox;
    private javax.swing.JButton polygamyHelp;
    private javax.swing.JCheckBox subpatternCkBox;
    private javax.swing.JButton subpatternHelp;
    private javax.swing.JCheckBox surnameCheckBox;
    // End of variables declaration//GEN-END:variables
}
