/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditTheoryFrame.java
 *
 * Created on Nov 11, 2011, 3:17:38 PM
 */
/**
 *
 * @author gary
 */
public class EditTheoryFrame extends javax.swing.JFrame {

    /** Creates new form EditTheoryFrame */
    public EditTheoryFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowTitle = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        authorName = new javax.swing.JTextField();
        citationLabel = new javax.swing.JLabel();
        citationScrollPane = new javax.swing.JScrollPane();
        citationText = new javax.swing.JTextArea();
        primitiveCombo = new javax.swing.JComboBox();
        stdMacroCombo = new javax.swing.JComboBox();
        primitiveInsertBtn = new javax.swing.JButton();
        stdMacroInsertBtn = new javax.swing.JButton();
        hornClauseScrollPane = new javax.swing.JScrollPane();
        hornClauseTextArea = new javax.swing.JTextArea();
        kinTermDefsCombo = new javax.swing.JComboBox();
        auxiliaryDefsCombo = new javax.swing.JComboBox();
        syntaxCheckBtn = new javax.swing.JButton();
        dyadCheckBtn = new javax.swing.JButton();
        acceptDefBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        windowTitle.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        windowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        windowTitle.setText("LangName Terms of Reference");

        authorLabel.setText("Primary Author:");

        authorName.setText("                                       ");
        authorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorNameActionPerformed(evt);
            }
        });

        citationLabel.setText("Citation:");

        citationText.setColumns(20);
        citationText.setRows(5);
        citationScrollPane.setViewportView(citationText);

        primitiveCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Predicates to Use", "daughter", "father", "mother", "etc." }));

        stdMacroCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Macros, Auxiliaries to Use", "half_brother", "step_mother", "etc." }));

        primitiveInsertBtn.setText("Insert");

        stdMacroInsertBtn.setText("Insert");

        hornClauseTextArea.setColumns(20);
        hornClauseTextArea.setRows(5);
        hornClauseTextArea.setText("oncle(Alter,Ego) :- parents(A,Ego), brother(Alter,A).\n  |  parents(A,Ego), sister(B,A), husband(Alter,B).");
        hornClauseScrollPane.setViewportView(hornClauseTextArea);

        kinTermDefsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kin Terms (defined & undefined)", "term1", "term2", "term3" }));

        auxiliaryDefsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auxilliary Terms", "gen[aux]", "cross[aux]", "etc." }));

        syntaxCheckBtn.setText("Syntax Check");

        dyadCheckBtn.setText("Dyad Check");

        acceptDefBtn.setText("Accept Def'n");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, hornClauseScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(kinTermDefsCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 302, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(37, 37, 37)
                        .add(auxiliaryDefsCombo, 0, 302, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(authorLabel)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(authorName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 288, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(citationLabel)
                            .add(18, 18, 18)
                            .add(citationScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 569, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                            .add(windowTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 314, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(169, 169, 169)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(primitiveCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 218, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(primitiveInsertBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                        .add(stdMacroCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(stdMacroInsertBtn)))
                .addContainerGap(42, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(56, 56, 56)
                .add(syntaxCheckBtn)
                .add(109, 109, 109)
                .add(dyadCheckBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 113, Short.MAX_VALUE)
                .add(acceptDefBtn)
                .add(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(windowTitle)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(authorLabel)
                    .add(authorName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(citationLabel)
                    .add(citationScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(kinTermDefsCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(auxiliaryDefsCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(hornClauseScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(primitiveCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(primitiveInsertBtn)
                    .add(stdMacroInsertBtn)
                    .add(stdMacroCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(syntaxCheckBtn)
                    .add(dyadCheckBtn)
                    .add(acceptDefBtn))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void authorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTheoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTheoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTheoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTheoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EditTheoryFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptDefBtn;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorName;
    private javax.swing.JComboBox auxiliaryDefsCombo;
    private javax.swing.JLabel citationLabel;
    private javax.swing.JScrollPane citationScrollPane;
    private javax.swing.JTextArea citationText;
    private javax.swing.JButton dyadCheckBtn;
    private javax.swing.JScrollPane hornClauseScrollPane;
    private javax.swing.JTextArea hornClauseTextArea;
    private javax.swing.JComboBox kinTermDefsCombo;
    private javax.swing.JComboBox primitiveCombo;
    private javax.swing.JButton primitiveInsertBtn;
    private javax.swing.JComboBox stdMacroCombo;
    private javax.swing.JButton stdMacroInsertBtn;
    private javax.swing.JButton syntaxCheckBtn;
    private javax.swing.JLabel windowTitle;
    // End of variables declaration//GEN-END:variables
}
