/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HelpSuggestionsPanel.java
 *
 * Created on Sep 15, 2011, 4:52:54 PM
 */
/**
 *
 * @author gary
 */
public class HelpSuggestionsPanel extends javax.swing.JPanel {

    /** Creates new form HelpSuggestionsPanel */
    public HelpSuggestionsPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        titleLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        titleLabel.setText("Getting Suggestions and Acting On Them");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(61, 61, 61)
                .add(titleLabel)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(titleLabel)
                .addContainerGap(346, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
